[build]
  base = "netlify-node"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/rasterize"
  status = 200
  force = true