[build]
  base    = "netlify-node"
  command = "node ../scripts/embed-font.mjs netlify/functions/font-data.js"

[functions]
  directory    = "netlify/functions"
  node_bundler = "nft"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/rasterize"
  status = 200
  force  = true