#!/usr/bin/env node
// scripts/embed-font.mjs
//
// Reads core/NotoSans-Subset.ttf and writes a JS module that exports the font
// as a Buffer. Pass the output path as the first argument.
//
// Usage (from project sub-root, e.g. netlify-node/ or vercel-node/):
//   node ../scripts/embed-font.mjs netlify/functions/font-data.js
//   node ../scripts/embed-font.mjs api/font-data.js

import fs   from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const [,, outArg] = process.argv;
if (!outArg) {
    console.error('Usage: embed-font.mjs <output-path>');
    process.exit(1);
}

const fontPath = path.resolve(__dirname, '../core/NotoSans-Subset.ttf');
const outPath  = path.resolve(process.cwd(), outArg);

const b64 = fs.readFileSync(fontPath).toString('base64');

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(
    outPath,
    `// Auto-generated by scripts/embed-font.mjs — do not edit\n` +
    `export const FONT_BUFFER = Buffer.from(\n` +
    `  "${b64}",\n` +
    `  "base64"\n` +
    `);\n`
);

console.log(`[embed-font] Wrote ${(b64.length * 0.75 / 1024).toFixed(0)} KB font → ${outPath}`);